# Generated by Django 2.2.3 on 2020-03-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='big_data_url',
            field=models.URLField(help_text='URL used for bigDataUrl in trackDb.txt', max_length=1000),
        ),
    ]
